name: sdm
description: A Flutter application for Social Distance Monitoring using Camera and Bluetooth.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_spinkit: ^4.1.2
  quartet: ^0.1.1
  camera: ^0.5.8+8
  tflite: ^1.1.1
  native_device_orientation: ^0.4.3
  flutter_bluetooth_serial:
  flutter_local_notifications: ^0.6.0
  path_provider: ^0.5.0+1
  system_settings:
  provider: ^2.0.1
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: true
  ios: true
  image_path: "images/playstore2.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
    - assets/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ElMessiri
      fonts:
        - asset: fonts/ElMessiri-Bold.ttf
        - asset: fonts/ElMessiri-Regular.ttf
        - asset: fonts/ElMessiri-Medium.ttf
        - asset: fonts/ElMessiri-SemiBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
